### ISSUE TITLE
Lot of trucks are spawing

### ISSUE THREAD

**Issue by bert0rdev** [89pleasure/cities2-realistic-density#10]
Hi,

since i started using your mod, i've got the following issue (see screenshot).
Is there a way to adjust the traffic spawn rate? I was wondering why trucks are heading to houses as well... is that intended?
![05-März-16-43-26-00](https://github.com/89pleasure/cities2-realistic-density/assets/20090544/8a605b50-0157-4124-a913-a08e148cefa2)

**Comment by 89pleasure** [comment]
Hey there! this is a vanilla bug and has nothing to do with my mod. It randomly appears and is not yet fixed by colossal order.
