### ISSUE TITLE
School/Education student count is not updating

### ISSUE THREAD

**Issue by Flow-Gee** [89pleasure/cities2-realistic-density#12]
School/Education student count of schools (observed on primary and secondary schools) is not updating, only after reloading a save game, the numbers are updated once.

**Comment by 89pleasure** [comment]
The numbers are only updating on new placed buildings. If you did place the building before using RealisticDensity it won't have the new values.

**Comment by Flow-Gee** [comment]
I started a completely new game with the mod activated and then placed the schools.

What I just witnessed is: The student count did indeed changed a little during the last hour (in the range of about 60±10), but then after reloading a save game it shoot up to 725. 

Something seems to be wrong with the updating of the student count display.

I try to take a screenshot next time.

**Comment by Flow-Gee** [comment]
Here a video of the bug:
https://streamable.com/hfhbw7?src=player-page-share

**Comment by 89pleasure** [comment]
Oh i didnt read it correctly, sorry! The mod does not change anything on the student count numbers. It only changes the workspaces. If you want to increase school student capacity you can use School Capacity Balancer by Wayz.
