### ISSUE TITLE
stürzt ab seit 0.8 

### ISSUE THREAD

**Issue by rein258** [89pleasure/cities2-realistic-density#2]
spiel Startet nicht mehr seit Update

**Comment by turastangras** [comment]
same here. used on an existing city. it crashes when loading the save-game. if you ignore the errors, you can continue playing without further problems (don't know, if it still works as expected though)

**Comment by cubanbread3** [comment]
You can ignore the error but the game eventually crashes. Posted a new entry with error capture from in-game.

**Comment by 89pleasure** [comment]
see #1
