### ISSUE TITLE
Huge Log file

### ISSUE THREAD

**Issue by Rene123** [89pleasure/cities2-realistic-density#4]
> [2024-01-04 19:22:33,953] [INFO]  Loading.
> [2024-01-04 19:22:33,953] [INFO]  Loading Harmony patches.
> [2024-01-04 19:22:34,004] [INFO]  Plugin RealisticDensity is loaded! Patched methods 2
> [2024-01-04 19:22:34,004] [INFO]  Patched method: Game.dll:Initialize
> [2024-01-04 19:22:34,004] [INFO]  Patched method: Game.dll:Initialize
> [2024-01-04 19:23:00,899] [INFO]  Add system to world.
> [2024-01-04 19:27:28,791] [INFO]  Run UpdateCityServicesJob
> [2024-01-04 19:27:28,793] [INFO]  Run UpdateSpawnablesJob
> [2024-01-04 19:27:28,795] [INFO]  Run UpdateHighOfficesJob
> [2024-01-04 19:27:28,895] [INFO]  Run UpdateSpawnablesJob
>..
> [2024-01-04 19:30:17,780] [INFO]  Run UpdateSpawnablesJob

This is the start of my log file, and after the Run UpdateSpawnablesJob goes on forever. See just 3 minutes of the game, and it has a log of nearly 500k already with Run UpdateSpawnablesJob on every line

**Comment by 89pleasure** [comment]
Which log file you mean exactly?
Do you play in dev mode?

**Comment by 89pleasure** [comment]
Fixed with #5
