### ISSUE TITLE
Disaster Response Vehicles in Maintenance when using mod

### ISSUE THREAD

**Issue by Mimonsi** [89pleasure/cities2-realistic-density#6]
When having this mode installed building a fire station and adding the disaster response unit puts all disaster response vehicles in maintenance. Efficiency is > 100%, 160/160 employees, but no matter how many response units or fire stations I build, the vehicles are not being used. 

Maybe it is unrelated to the mod, but I can reproduce it.

**Comment by 89pleasure** [comment]
All vehicles aren't used? Does it only happen if you upgrade the building with disaster response unit, or does it not matter?

**Comment by Mimonsi** [comment]
The fire station has 10 vehicles per default (0 in maintenance). As soon as I add the disaster response unit the total vehicle count is 15 and 5 vehicles are in maintenance. This repeates no matter how many disaster response units I add, with 4 disaster response units there is a total of 30 vehicles (20 in maintenance)

**Comment by 89pleasure** [comment]
Okay, i did check it with vanilla game, without any mods. Happens there too, so this is not related to RealisticDensity mod.
Please check first if a potential bug only happens with the mod activated.

**Comment by Mimonsi** [comment]
I check with vanilla and it didn't happen there, but probably just CO inconsistency then.

**Comment by 89pleasure** [comment]
Hm, that's odd. Maybe I do miss something here. I repopen the issue again. Maybe there is something weird going on.

**Comment by Mimonsi** [comment]
I am going to ahead and close this issue, after further testing I have found this issue to be related to EconomyFixer and **not** Realistic Density!
